# Generated by Django 2.2.4 on 2019-08-15 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190815_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='blurb',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
